Name:           claude-desktop
Version:        %{_version}
Release:        1%{?dist}
Summary:        Claude Desktop (unofficial Linux repackage)
License:        Proprietary
URL:            https://claude.ai
BuildArch:      x86_64
AutoReqProv:    no

# build-packages.sh injects --define "_version <ver>" and --define "_buildroot <dir>"
# so we work directly with a pre-populated BUILDROOT and skip the prep/build phases.

Requires:       electron
Requires:       xdg-utils
Requires:       bash

%description
Unofficial repackage of the macOS Claude Desktop application for Linux.
Extracts app.asar from the official macOS DMG, replaces macOS-native Node
addons with pure-JS stubs, and patches the Cowork platform gate so Claude
Code runs directly on Linux (no VM).

Cowork isolation uses bubblewrap by default (COWORK_BACKEND=bubblewrap).
Set COWORK_BACKEND=host to disable the sandbox.

This package requires a system-installed `electron` binary.
See /usr/lib/claude-desktop/ELECTRON_VERSION for the required version.

%prep
# No-op: build-packages.sh pre-populates %{buildroot}.

%build
# No-op.

%install
# The BUILDROOT is pre-populated by build-packages.sh.
# rpmbuild owns the directory; nothing to copy here.

%post
# Register the claude:// URI scheme.
if command -v xdg-mime &>/dev/null; then
  xdg-mime default claude-desktop.desktop x-scheme-handler/claude || true
fi

# Update desktop database.
if command -v update-desktop-database &>/dev/null; then
  update-desktop-database -q /usr/share/applications || true
fi

# Create the /sessions symlink required by the path translator.
# We create it at the system level so it persists across reboots.
if [[ ! -L /sessions ]]; then
  SESSION_TARGET="$HOME/.local/share/claude-linux/sessions"
  mkdir -p "$SESSION_TARGET"
  ln -sf "$SESSION_TARGET" /sessions 2>/dev/null || \
    echo "claude-desktop: could not create /sessions symlink — run as root or create it manually:"
    echo "  sudo ln -sf ~/.local/share/claude-linux/sessions /sessions"
fi

%preun
if command -v update-desktop-database &>/dev/null; then
  update-desktop-database -q /usr/share/applications || true
fi

%files
%defattr(-,root,root,-)
/usr/bin/claude-desktop
/usr/lib/claude-desktop/
/usr/share/applications/claude-desktop.desktop
/usr/share/icons/hicolor/

%changelog
# Changelog is auto-generated by build-packages.sh from the upstream version.
